FROM owncloud/base:20.04-arm64v8@sha256:08ceed5ffba64a6b6dcbc9373befb048bad921a2b3bb137cc88016077572795e

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud QNAP" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/qnap" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/qnap" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/qnap"

VOLUME ["/mnt/data"]
EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/owncloud", "server"]

ADD owncloud.tar.bz2 /var/www/
ADD qnap.tar.gz /var/www/owncloud/apps/
ADD theme-qnap.tar.gz /var/www/owncloud/apps/

COPY ./overlay /
WORKDIR /var/www/owncloud

RUN find /var/www/owncloud \( \! -user www-data -o \! -group root \) -print0 | xargs -r -0 chown www-data:root && \
  chmod g+w /var/www/owncloud
