FROM owncloud/base:20.04-amd64@sha256:41ede2bf6b1c46f8b0db7f18191e1e046655f7af6680f23f6ae7eb21d0a6a7b9

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud QNAP" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/qnap" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/qnap" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/qnap"

VOLUME ["/mnt/data"]
EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/owncloud", "server"]

ADD owncloud.tar.bz2 /var/www/
ADD qnap.tar.gz /var/www/owncloud/apps/
ADD theme-qnap.tar.gz /var/www/owncloud/apps/

COPY ./overlay /
WORKDIR /var/www/owncloud

RUN find /var/www/owncloud \( \! -user www-data -o \! -group root \) -print0 | xargs -r -0 chown www-data:root && \
  chmod g+w /var/www/owncloud
