FROM owncloud/base:20.04-amd64@sha256:227c42147513a6ee41d887d7a7e87a8f9e562f72f5f3071f76f30f5f3a592e1c

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud QNAP" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/qnap" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/qnap" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/qnap"

VOLUME ["/mnt/data"]
EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/owncloud", "server"]

ADD owncloud.tar.bz2 /var/www/
ADD qnap.tar.gz /var/www/owncloud/apps/
ADD theme-qnap.tar.gz /var/www/owncloud/apps/

COPY ./overlay /
WORKDIR /var/www/owncloud

RUN find /var/www/owncloud \( \! -user www-data -o \! -group root \) -print0 | xargs -r -0 chown www-data:root && \
  chmod g+w /var/www/owncloud
