FROM owncloud/base:20.04-arm32v7@sha256:9228940622c5973127c1674a00f8feb1f9435ac5c3e0781fcb1ef08b11c91a62

ARG DOC_VERSION=10.10
ENV DOC_VERSION ${DOC_VERSION}

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud QNAP" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/qnap" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/qnap" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/qnap"

VOLUME ["/mnt/data"]
EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/owncloud", "server"]

ADD owncloud.tar.bz2 /var/www/
ADD qnap.tar.gz /var/www/owncloud/apps/
ADD theme-qnap.tar.gz /var/www/owncloud/apps/
#ADD ["https://doc.owncloud.com/pdf/server/${DOC_VERSION}_ownCloud_Admin_Manual.pdf", "/var/www/owncloud/skeleton/${DOC_VERSION}_ownCloud_Admin_Manual.pdf"]
#ADD ["https://doc.owncloud.com/pdf/server/${DOC_VERSION}_ownCloud_User_Manual.pdf", "/var/www/owncloud/skeleton/${DOC_VERSION}_ownCloud_User_Manual.pdf"]

ADD overlay /
WORKDIR /var/www/owncloud

RUN find /var/www/owncloud \( \! -user www-data -o \! -group root \) -print0 | xargs -r -0 chown www-data:root && \
  chmod g+w /var/www/owncloud
